---
# tasks file for metrics
- block:
    - name: Create metrics data directory
      file:
        name: "{{ item }}"
        state: directory
        mode: "0755"
      with_items:
        - "{{ addon.location }}/metrics"

    - name: Deployment metrics --- part.1
      template:
        src: metrics.yaml.j2
        dest: "{{ addon.location }}/metrics/metrics.yaml"

    - name: Deployment metrics --- part.2
      shell: "/usr/local/bin/kubectl apply -f {{ addon.location }}/metrics/metrics.yaml"
      run_once: true
  when: addon.metrics
