---
# tasks file for canal
- block:
    - name: Create canal data directory
      file:
        name: "{{ addon.location }}/canal"
        state: directory
        mode: "0755"

    - name: Deployment canal --- part.1
      template:
        src: canal.yaml.j2
        dest: "{{ addon.location }}/canal/canal.yaml"

    - name: Deployment canal --- part.2
      shell: "/usr/local/bin/kubectl apply -f {{ addon.location }}/canal/canal.yaml"
      run_once: true
  when: addon.network == "canal"
