---
# tasks file for flannel
- block:
    - name: Create flannel data directory
      file:
        name: "{{ addon.location }}/flannel"
        state: directory
        mode: "0755"

    - name: Deployment flannel --- part.1
      template:
        src: flannel.yaml.j2
        dest: "{{ addon.location }}/flannel/flannel.yaml"

    - name: Deployment flannel --- part.2
      shell: "/usr/local/bin/kubectl apply -f {{ addon.location }}/flannel/flannel.yaml"
      run_once: true
  when: addon.network == "flannel"
