---
# tasks file for cilium
- block:
    - name: Create cilium data directory
      file:
        name: "{{ addon.location }}/cilium"
        state: directory
        mode: "0755"

    - name: Deployment cilium --- part.1
      template:
        src: cilium.yaml.j2
        dest: "{{ addon.location }}/cilium/cilium.yaml"

    - name: Deployment cilium --- part.2
      shell: "/usr/local/bin/kubectl apply -f {{ addon.location }}/cilium/cilium.yaml"
      run_once: true
  when: addon.network == "cilium"
